/*import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });*/

// i commented the above code out because i manually intergrated inter font, i dont think i needed it again

import { 
  ClerkProvider,
} from "@clerk/nextjs";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
     <html lang="en">
       <body>{children}</body>
     </html>
    </ClerkProvider>
  );
}

